# NOTE: Do not edit, file was generated by jhconvert

Name: etoys
Version: 4.0.2229
Release: %mkrel 1
Summary: An educational tool for teaching children powerful ideas in compelling ways
License: MIT/Apache
Group: Graphical desktop/Other
Url: http://squeakland.org/

Source: http://download.sugarlabs.org/sources/sucrose/glucose/etoys/etoys-4.0.2229.tar.gz

Patch: etoys-4.0.2229-sugar-etoys-desktop.patch

Requires: squeak-vm-olpc >= 3.10.3

BuildRequires: autoconf  
BuildRequires: automake  
BuildRequires: gettext  
BuildRequires: libtool  

BuildRoot: %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch: noarch

%description
Squeak Etoys was inspired by LOGO, PARC-Smalltalk, Hypercard, starLOGO
and AgentSheets. It is a media-rich authoring environment with a simple,
powerful scripted object model for many kinds of objects created by end-users
that runs on many platforms, and it is free and open source. It includes 2D and
3D graphics, images, text, particles, presentations, web-pages, videos, sound
and MIDI, etc. It includes the ability to share desktops with other Etoy users
in real-time, so many forms of immersive mentoring and play can be done over
the Internet.

%prep
%setup -q -n etoys-4.0.2229
%patch -p1

%build
autoreconf
%define __libtoolize true
%configure --exec_prefix=%{_prefix}/bin --datarootdir=%{_prefix}/share --datadir=%{_prefix}/share --bindir=%{_prefix}/bin
make

%install
rm -rf %{buildroot}
make ROOT=%{buildroot} datadir=%{buildroot}/%{_prefix}/share bindir=%{buildroot}/%{_prefix}/bin install-etoys


%clean
rm -rf %{buildroot}

%files 
%defattr(-,root,root,-)
%{_bindir}/*
%{_datadir}/etoys
%{_datadir}/mime/packages/*
%{_datadir}/doc/*
%{_datadir}/applications/*

